FROM dvilela/hummingbot-api-marlin-base@sha256:abb76f79d3265e51be7d3d726730d3959e4b8629eabecc9b5c0b8ef384f957c0

WORKDIR /hummingbot-api

ARG COWSWAP_CONNECTOR_COMMIT=2472d0ba951375712d44179a8e0aea0cfef8be78
RUN pip install --no-cache-dir --force-reinstall --no-deps \
    "hummingbot-cowswap-connector @ git+https://github.com/dvilelaf/hummingbot-dex-connectors.git@${COWSWAP_CONNECTOR_COMMIT}#subdirectory=cowswap"

COPY main.py config.py deps.py ./
COPY models ./models
COPY routers ./routers
COPY services ./services
COPY utils ./utils
COPY database ./database
COPY bots/controllers ./bots/controllers
COPY bots/scripts ./bots/scripts
COPY docker/hyperliquid-runtime-patch.py /tmp/hyperliquid-runtime-patch.py
COPY docker/xrpl-runtime-patch.py /tmp/xrpl-runtime-patch.py

RUN python /tmp/hyperliquid-runtime-patch.py && rm /tmp/hyperliquid-runtime-patch.py && \
    python /tmp/xrpl-runtime-patch.py && rm /tmp/xrpl-runtime-patch.py
